// Auto-generated by scripts/build-skill-versions.ts — do not edit.
export const skillChangelog = `# Skills Changelog

All notable changes to the bundled \`skills/\` directory.

The bundle ships as a single versioned unit (semver in \`skills/VERSION\`).
No per-skill versions — bump-skill-versions patch-bumps the bundle when
any file under \`skills/<name>/**\` changes.

## [0.1.0] — 2026-05-22

Initial brain skills bundle.

### New skills

- \`brain-search\` — semantic + bitemporal search workflow for AI agents
- \`brain-recall\` — entity profile + timeline + connections workflow
- \`brain-bitemporal\` — formulating \`asOf\` queries and reading retracted facts
- \`brain-mcp-setup\` — connect a new MCP client to brain (Claude Desktop / Cursor / Goose)
`;
